export const clerkAppearance = {
  cssLayerName: "clerk",
  variables: {
    colorPrimary: "#1d1b18",
    colorBackground: "#f7f4ee",
    colorForeground: "#1d1b18",
    colorMutedForeground: "#7d7568",
    colorMuted: "#efeae0",
    colorInput: "#efeae0",
    colorBorder: "#cdc6b8",
    colorDanger: "#8a4a3c",
    borderRadius: "0.75rem",
    fontFamily: "var(--font-inter), system-ui, sans-serif",
  },
  elements: {
    headerTitle: "font-serif",
    formButtonPrimary: "rounded-full normal-case text-sm font-medium shadow-none",
    footerActionLink: "text-[#7a5c3e] hover:text-[#1d1b18]",
    footer: "hidden",
    badge: "!hidden",
    cardBox: "shadow-none border-none bg-transparent w-full",
    card: "shadow-none border-none bg-transparent p-0 w-full gap-5",
    rootBox: "w-full",
    header: "gap-2",
    main: "gap-5",
    socialButtons: "gap-3",
    socialButtonsBlockButton: "rounded-full normal-case text-sm font-medium shadow-none",
    formFieldInput: "rounded-xl",
    form: "gap-5",
  },
};
